theme: jekyll-theme-slate
title: Obrada dostavljenih podataka - UQ regulacija na sučelju u HE Zakučac
description:  
remote_theme: sighingnow/jekyll-gitbook
plugins:
- jekyll-remote-theme
include:
  - assets/css
toc:
    enabled: true
collections:
  pages:
    output: true        # Makes pages render as actual output
    permalink: /:name/  # Creates clean URLs based on file names
header_sections:
  - label: "Agregat A"
    links:
      - title: "KONČAR PROCIS"
        url: "/uq-reg-gen-a-procis/"
        class: "green-link"        
      - title: "INEM"
        url: "/uq-reg-gen-a-inem/"
        class: "green-link"
  - label: "Agregat D"
    links:
      - title: "KONČAR PROCIS"
        url: "/uq-reg-gen-d-procis/"
        class: "green-link"
      - title: "INEM"
        url: "/uq-reg-gen-d-inem/"
        class: "green-link"